sudo: false
dist: trusty
language: java
jdk:
  - oraclejdk8
before_install:
  - "export ORG_GRADLE_PROJECT_ideaVersion=${IDEA}"
  - "export ORG_GRADLE_PROJECT_phpPluginVersion=${PHP}"
install:
  echo "install skip"
matrix:
  include:
    - name: "latest"
      env: IDEA="IU-2019.2.3" PHP="192.6817.12" DEPLOY=true
    - name: "2018"
      env: IDEA="IU-2019.1.4" PHP="191.8026.56"
  allow_failures:
    - name: "EAP Tests"
      env: IDEA="IU-LATEST-EAP-SNAPSHOT" PHP="191.7479.51"
script:
  - ./gradlew check buildPlugin checkReadme
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
  timeout: 3600
deploy:
  - provider: script
    script: "export ORG_GRADLE_PROJECT_version=$(date +%Y.%-m.%-d%H%M%S) ; ./gradlew buildPlugin deployNightly"
    skip_cleanup: true
    on:
      branch: master
      condition: $DEPLOY = true
