sudo: false
dist: trusty
language: java
jdk:
  - oraclejdk8
before_install:
- "export ORG_GRADLE_PROJECT_ideaVersion=${IDEA}"
- "export ORG_GRADLE_PROJECT_phpPluginVersion=${PHP}"
- "export ORG_GRADLE_PROJECT_version=$(date +%Y.%-m.%-d%H%M%S)"
matrix:
  include:
    - name: "Stable Test"
      env: IDEA="IU-182.4505.22" PHP="182.4129.45"
      script:
        - ./gradlew check buildPlugin patchRepositoryXml
        - curl --max-time 15 -T "{build/libs/PhpClean.jar,build/libs/PhpClean-nightly.xml}" -u $ftp_login:$ftp_password ftp://$ftp_host/
    - name: "EAP Tests"
      env: IDEA="IU-LATEST-EAP-SNAPSHOT" PHP="183.4284.150"
      script:
        - ./gradlew check buildPlugin
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
  timeout: 3600