name: Build

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        idea: [ "IU-2020.1.2" ]
        php: [ "201.7846.64" ]
        include:
          - idea: "IU-LATEST-EAP-SNAPSHOT"
            php: "202.5103.13"
            experimental: true

    name: Build Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build the plugin
        run: ./gradlew buildPlugin
        env:
            ORG_GRADLE_PROJECT_ideaVersion: ${{ matrix.idea }}
            ORG_GRADLE_PROJECT_phpPluginVersion: ${{ matrix.php }}

      - name: Verify Plugin Compatilibity on IntelliJ Platform
        id: verify
        uses: ChrisCarini/intellij-platform-plugin-verifier-action@v0.0.2
        with:
          ide-versions: |
            ideaIU:2019.3
            ideaIC:LATEST-EAP-SNAPSHOT

      - name: Get log file path and print contents
        run: |
          echo "The verifier log file [${{steps.verify.outputs.verification-output-log-filename}}] contents : " ;
          cat ${{steps.verify.outputs.verification-output-log-filename}}
